app = "speech-app"

[build]
  dockerfile = "Dockerfile"

[env]
  DEEPGRAM_API_KEY=cb7a1c90deaea3cf954383c68c7c18a3fa9a3db2
  SUPABASE_URL=https://daooyvthvcxvvawldqnl.supabase.co
  SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhb295dnRodmN4dnZhd2xkcW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDM5MTYsImV4cCI6MjA2NDAxOTkxNn0.qYFwk34F9zjs74PhwsCtaYJcPMwq-48qx7473xDrzYo

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
