# fly.toml app configuration file generated for speech-app-v4qrwq on 2025-05-29T00:23:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'speech-app-v4qrwq'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
